# Generated by Django 5.2.12 on 2026-03-03 17:06

import django.contrib.postgres.search
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Ensure pgvector extension exists (also created by Docker init script)
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                (
                    "content_tsv",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "source",
                    models.CharField(db_index=True, default="manual", max_length=50),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("importance", models.FloatField(default=0.5)),
                ("decay_factor", models.FloatField(default=1.0)),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="memory_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                    models.Index(fields=["-created_at"], name="memory_created_at_idx"),
                ],
            },
        ),
        # GIN index on content_tsv for full-text search
        migrations.RunSQL(
            "CREATE INDEX memory_content_tsv_gin ON core_memory USING gin (content_tsv);",
            reverse_sql="DROP INDEX IF EXISTS memory_content_tsv_gin;",
        ),
        # GIN index on tags for tag filtering
        migrations.RunSQL(
            "CREATE INDEX memory_tags_gin ON core_memory USING gin (tags);",
            reverse_sql="DROP INDEX IF EXISTS memory_tags_gin;",
        ),
        # Trigger: auto-update content_tsv when content changes
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION core_memory_tsv_trigger() RETURNS trigger AS $$
                BEGIN
                    NEW.content_tsv := to_tsvector('english', NEW.content);
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER core_memory_content_tsv_update
                    BEFORE INSERT OR UPDATE OF content ON core_memory
                    FOR EACH ROW EXECUTE FUNCTION core_memory_tsv_trigger();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS core_memory_content_tsv_update ON core_memory;
                DROP FUNCTION IF EXISTS core_memory_tsv_trigger();
            """,
        ),
    ]
